### ISSUE TITLE
ALLOW SAMPLES TO BE SCANNED WHEN STORING 

### ISSUE THREAD

**Issue by tumiemosweu** [senaite/senaite.storage#10]
## Steps to reproduce
-Go to store samples
-Select storage facility
-Select freezer
-Select rack
-Select box
-Add sample

## Current behavior
-You select a sample from the list in order to store it

## Expected behavior
-Add an option to scan a sample into a position within a box

**Comment by xispa** [comment]
Fixed in https://github.com/senaite/senaite.storage/pull/9
