### ISSUE TITLE
Senaite.storages crashes when using German umlauts (i.e. "ö")

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.storage#3]
## Steps to reproduce
LIMS/Core version: 1.3.0
Storage version: 1.0.0

If a container with German umlauts is created and saved, senaite.storage crashes, whenever the container is clicked to open it.  The name of the container containing German umlauts can not be changed afterwards to circumvent this problem. 

![2019-05-06 14_13_03-Ubuntu-16 04 3 - VMware Workstation](https://user-images.githubusercontent.com/38714119/57224252-21776480-7009-11e9-8007-0fde72161f69.png)

![2019-05-06 14_08_23-Ubuntu-16 04 3 - VMware Workstation](https://user-images.githubusercontent.com/38714119/57224102-91391f80-7008-11e9-9f8f-2ba5299e0471.png)

## Current behavior

Senaite.storage crashes.

## Expected behavior

Should not crash

## Screenshot (optional)

see above

**Comment by ramonski** [comment]
This should work for new versions w/o problems.
