### ISSUE TITLE
Error When Installing Add-on

### ISSUE THREAD

**Issue by noblelabs1** [senaite/senaite.storage#31]
## Steps to reproduce
Included senaite.storage in buildout.cfg
killed instance
reran buildout
started instance
tried to install from admin add-on area
## Current behavior
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 689, in __call__
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 454, in install_product
  Module Products.GenericSetup.tool, line 405, in runAllImportStepsFromProfile
   - __traceback_info__: profile-senaite.storage:default
  Module Products.GenericSetup.tool, line 1492, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1339, in _doRunHandler
  Module senaite.storage.setuphandlers, line 200, in post_install
  Module senaite.storage.setuphandlers, line 340, in setup_workflows
  Module senaite.storage.setuphandlers, line 353, in update_workflow
  Module senaite.storage.setuphandlers, line 362, in update_workflow_state
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by ramonski** [comment]
Closing this one as it can not be reproduced in new versions
