### ISSUE TITLE
Storage page access management

### ISSUE THREAD

**Issue by toropok** [senaite/senaite.storage#33]
Hi

Seems like the storage page is available to any user for viewing at least (for clients for example). How we can manage access rights for this page?

--loe

**Comment by xispa** [comment]
Thanks @toropok for reporting. #34 resolves the issue, you need to upgrade the source code and run upgrade step 2.2.0 for `senaite.storage` from ZMI (e.g. http://localhost:8080/senaite/portal_setup/manage_upgrades) once merged.

**Comment by toropok** [comment]
@xispa thank you!

works fine :)
