### ISSUE TITLE
Adding samples to container does not work

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.storage#5]
## Steps to reproduce
Adding samples to container (for example at position A1)

![2019-05-07 07_37_59-Ubuntu-16 04 3 - VMware Workstation](https://user-images.githubusercontent.com/38714119/57274357-4ddbc100-709b-11e9-8c91-e1d1cc69062b.png)

## Current behavior
Following error message occurs (No position or not valid sample selected):

![2019-05-07 07_39_00-Ubuntu-16 04 3 - VMware Workstation](https://user-images.githubusercontent.com/38714119/57274376-5df3a080-709b-11e9-9855-e62b6cf656a2.png)

## Expected behavior
Adding of samples should be possible. Should work for samples with and without existing AR.

**Comment by Migulo** [comment]
LIMS/Core version: 1.3.0
Storage version: 1.0.0

**Comment by Migulo** [comment]
Update: Adding works for already existing AR-samples --> feature request for the possibility to add samples without AR requests. The reason for this is, that in our laboratory the analysis taken are depending on priority, resources and severity and might change or might completely skipped. --> Storage function should be independent from analysis.

**Comment by ramonski** [comment]
Closing this one as it should work with new versions of senaite.storage
